language: node_js
node_js:
- 10
before_install:
- npm install -g npm
script:
- npm install
- npm test
deploy:
  provider: heroku
  api_key: 1718e542-5505-4e31-a14d-b27514635f92
  app: hello-node-boris
  on:
    repo: schin211/hello-node-boris
    branch: master
